module.exports = {
  UPDATE_REGION_DATA: 'UPDATE_REGION_DATA',
  GET_REGION_DATA: 'GET_REGION_DATA',
  GET_REGION_DATA_SUCCESS: 'GET_REGION_DATA_SUCCESS',
  GET_REGION_DATA_FAILURE: 'GET_REGION_DATA_FAILURE',
}
